// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';
import { warning } from 'F:/oceanh_workspace/Project/pixie-ui/node_modules/.pnpm/rc-util@5.44.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/rc-util';
import { SiteContext, type ISiteContext } from 'F:/oceanh_workspace/Project/pixie-ui/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.10_@swc+helpers@0.5.1_@types+node@20.17.24_@types+react@18.3.18__3rbzvs7fy27yec7umls4oc3uwm/node_modules/dumi/dist/client/theme-api/context.js';
import { components } from '../meta/atoms';
import { locales } from '../locales/config';



const entryExports = {
};

// Static content
const pkg = {"name":"@pixie-ui/docs","description":"Pixie UI组件库文档","version":"0.0.1"};
const historyType = "browser";
const hostname = undefined;
const themeConfig = {"footer":"Copyright © 2025 | Powered by <a href=\"https://d.umijs.org\" target=\"_blank\" rel=\"noreferrer\">dumi</a>","prefersColor":{"default":"light","switch":true},"nprogress":true,"lastUpdated":true,"name":"Pixie UI","logo":"/logo.png","nav":[{"title":"指南","link":"/guide"},{"title":"组件","link":"/components"}],"sidebar":{"/guide":[{"title":"介绍","children":[{"title":"什么是 Pixie UI","link":"/guide/introduction"},{"title":"快速上手","link":"/guide/getting-started"}]},{"title":"设计","children":[{"title":"设计原则","link":"/guide/design-principles"},{"title":"主题定制","link":"/guide/theming"}]}],"/components":[{"title":"通用","children":[{"title":"Button 按钮","link":"/components/button"},{"title":"Input 输入框","link":"/components/input"}]}]},"socialLinks":{"github":"https://github.com/Ocean-H1/pixie-ui"}};
const _2_level_nav_available = true;

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(false);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  const context: ISiteContext = React.useMemo(() => {
    const ctx = {
      pkg,
      historyType,
      entryExports,
      demos: null,
      components,
      locales,
      loading,
      setLoading,
      hostname,
      themeConfig,
      _2_level_nav_available,
    };

    // Proxy do not warning since `Object.keys` will get nothing to loop
    Object.defineProperty(ctx, 'demos', {
      get: () => {
        warning(false, '`demos` return empty in latest version, please use `useDemo` instead.');
        return {};
      },
    });

    return ctx;
  }, [
    pkg,
    historyType,
    entryExports,
    components,
    locales,
    loading,
    setLoading,
    hostname,
    themeConfig,
    _2_level_nav_available,
  ]);

  return (
    <SiteContext.Provider value={context}>
      {outlet}
    </SiteContext.Provider>
  );
}
