// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from 'F:/oceanh_workspace/Project/pixie-ui/apps/doc/docs/guide/getting-started.md?type=frontmatter';
import { demoIndex as dmi0 } from 'F:/oceanh_workspace/Project/pixie-ui/apps/doc/docs/guide/getting-started.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from 'F:/oceanh_workspace/Project/pixie-ui/apps/doc/docs/guide/introduction.md?type=frontmatter';
import { demoIndex as dmi1 } from 'F:/oceanh_workspace/Project/pixie-ui/apps/doc/docs/guide/introduction.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from 'F:/oceanh_workspace/Project/pixie-ui/apps/doc/docs/components/button.md?type=frontmatter';
import { demoIndex as dmi2 } from 'F:/oceanh_workspace/Project/pixie-ui/apps/doc/docs/components/button.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from 'F:/oceanh_workspace/Project/pixie-ui/apps/doc/docs/components/input.md?type=frontmatter';
import { demoIndex as dmi3 } from 'F:/oceanh_workspace/Project/pixie-ui/apps/doc/docs/components/input.md?type=demo-index';

export const filesMeta = {
  'docs/guide/getting-started': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'F:/oceanh_workspace/Project/pixie-ui/apps/doc/docs/guide/getting-started.md?type=text'),
  },
  'docs/guide/introduction': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'F:/oceanh_workspace/Project/pixie-ui/apps/doc/docs/guide/introduction.md?type=text'),
  },
  'docs/components/button': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'F:/oceanh_workspace/Project/pixie-ui/apps/doc/docs/components/button.md?type=text'),
  },
  'docs/components/input': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'F:/oceanh_workspace/Project/pixie-ui/apps/doc/docs/components/input.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
