// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"GlobalLayout":{"id":"GlobalLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"GlobalLayout","isLayout":true},"docs/guide/getting-started":{"path":"guide/getting-started","id":"docs/guide/getting-started","parentId":"DocLayout"},"docs/guide/introduction":{"path":"guide/introduction","id":"docs/guide/introduction","parentId":"DocLayout"},"docs/components/button":{"path":"components/button","id":"docs/components/button","parentId":"DocLayout"},"docs/components/input":{"path":"components/input","id":"docs/components/input","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"GlobalLayout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'F:/oceanh_workspace/Project/pixie-ui/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.10_@swc+helpers@0.5.1_@types+node@20.17.24_@types+react@18.3.18__3rbzvs7fy27yec7umls4oc3uwm/node_modules/dumi/dist/client/pages/404.js')),
'GlobalLayout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__layouts__GlobalLayout" */'F:/oceanh_workspace/Project/pixie-ui/apps/doc/.dumi/theme/layouts/GlobalLayout.tsx')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'F:/oceanh_workspace/Project/pixie-ui/apps/doc/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'F:/oceanh_workspace/Project/pixie-ui/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.10_@swc+helpers@0.5.1_@types+node@20.17.24_@types+react@18.3.18__3rbzvs7fy27yec7umls4oc3uwm/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/guide/getting-started': React.lazy(() => import(/* webpackChunkName: "docs__guide__getting-started.md" */'F:/oceanh_workspace/Project/pixie-ui/apps/doc/docs/guide/getting-started.md')),
'docs/guide/introduction': React.lazy(() => import(/* webpackChunkName: "docs__guide__introduction.md" */'F:/oceanh_workspace/Project/pixie-ui/apps/doc/docs/guide/introduction.md')),
'docs/components/button': React.lazy(() => import(/* webpackChunkName: "docs__components__button.md" */'F:/oceanh_workspace/Project/pixie-ui/apps/doc/docs/components/button.md')),
'docs/components/input': React.lazy(() => import(/* webpackChunkName: "docs__components__input.md" */'F:/oceanh_workspace/Project/pixie-ui/apps/doc/docs/components/input.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'F:/oceanh_workspace/Project/pixie-ui/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.10_@swc+helpers@0.5.1_@types+node@20.17.24_@types+react@18.3.18__3rbzvs7fy27yec7umls4oc3uwm/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
