// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'F:/oceanh_workspace/Project/pixie-ui/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.10_@swc+helpers@0.5.1_@types+node@20.17.24_@types+react@18.3.18__3rbzvs7fy27yec7umls4oc3uwm/node_modules/dumi/theme-default/slots/Logo/index.js';
